
# build python wheels for windows

name: Build wheels

on: 
  push:
    tags:
      - '*' # 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3
      run: |
        echo "Building wheels for ${{ matrix.python-version }} on ${{ matrix.os }}"
        echo "Tag name: ${{ github.tag_name }}"     

# jobs:
#   build:
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python 3
#       uses: actions/setup-python@v3
#       with:
#         python-version: 3
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install wheel
#     - name: Build wheels
#       run: |
#         python setup.py bdist_wheel
#     - uses: actions/upload-artifact@v3
#       with:
#         name: wheels
#         path: dist/*.whl

  
#   upload:
#     needs: build
#     runs-on: windows-latest
#     steps:
#     - uses: actions/download-artifact@v3
#       with:
#         name: wheels
#         path: dist

#     - name: add to release
#       uses: svenstaro/upload-release-action@v2
#       with:
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
#         file: dist/*.whl
#         tag: ${{ github.ref }}
#         asset_name : ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-${{ matrix.python-version }}-${{ matrix.os }}.whl
#         overwrite: true
#         file_glob: true

